# Generated by Django 5.2.7 on 2025-11-06 17:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(50)]
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author", "created_at"],
                        name="articles_author__998909_idx",
                    ),
                    models.Index(
                        fields=["is_published", "created_at"],
                        name="articles_is_publ_552648_idx",
                    ),
                    models.Index(
                        fields=["tags", "is_published"], name="articles_tags_a053ab_idx"
                    ),
                    models.Index(
                        condition=models.Q(
                            ("is_deleted", False), ("is_published", True)
                        ),
                        fields=["title"],
                        name="idx_article_title_active",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("author", "title"),
                        name="unique_author_title",
                    )
                ],
            },
        ),
    ]
