# Generated by Django 5.2.7 on 2025-11-06 17:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "text",
                    models.TextField(
                        db_index=True,
                        max_length=1000,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="articles.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "article_comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "created_at"],
                        name="article_com_article_264ef9_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="article_com_user_id_f2034d_idx",
                    ),
                    models.Index(
                        fields=["article", "is_deleted", "created_at"],
                        name="article_com_article_9d543a_idx",
                    ),
                    models.Index(
                        fields=["user", "is_deleted", "created_at"],
                        name="article_com_user_id_9d6cc7_idx",
                    ),
                    models.Index(
                        fields=["article", "user", "created_at"],
                        name="article_com_article_20a65b_idx",
                    ),
                    models.Index(
                        condition=models.Q(("is_deleted", False)),
                        fields=["article", "created_at"],
                        name="idx_chronological_active",
                    ),
                ],
            },
        ),
    ]
