# Generated by Django 5.2.7 on 2025-11-06 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="articles.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "article_likes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="article_lik_user_id_a6b08f_idx",
                    ),
                    models.Index(
                        fields=["article", "created_at"],
                        name="article_lik_article_5b6afa_idx",
                    ),
                    models.Index(
                        fields=["user", "article", "is_deleted"],
                        name="article_lik_user_id_11cef7_idx",
                    ),
                    models.Index(
                        fields=["article", "is_deleted", "created_at"],
                        name="article_lik_article_c30c91_idx",
                    ),
                    models.Index(
                        condition=models.Q(("is_deleted", False)),
                        fields=["article"],
                        name="idx_active_likes_per_article",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("user", "article"),
                        name="unique_user_article_like",
                    )
                ],
            },
        ),
    ]
